# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190403_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
